version: '2'

services:

  dummydb:
    build:
      context: ../
      dockerfile: docker/dummydb/Dockerfile
    ports:
      - "1984:1984"
    networks:
      main:
        aliases:
          - dummydb

  explorer:
    build:
      context: ../
      dockerfile: docker/explorer/Dockerfile
    ports:
      - "5000:5000"
    networks:
      main:
        ipv4_address: 10.5.0.5
        aliases:
          - explorer
    depends_on:
      - bitcoin
      - elements
      - dummydb

  elements:
    build:
      context: ../
      dockerfile: docker/elements/Dockerfile
    volumes:
      - ../../explorer-data/elementsregtest:/root/.elements
    ports:
      - "7041:7041"
    networks:
      main:
        aliases:
          - elements

  bitcoin:
    build:
      context: ../
      dockerfile: docker/bitcoin/Dockerfile
    volumes:
      - ../../explorer-data/bitcoin:/root/.bitcoin
      - ../../explorer-data/testnet3:/root/.testnet3
    ports:
      - "8532:8532"
      - "18532:18532"
    networks:
      main:
        aliases:
          - bitcoin

networks:
  main:
    driver: bridge
    ipam:
      config:
      - subnet: 10.5.0.0/16
